// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DigitalDash-U5-Disco

#include "../ui.h"

void ui_view1_screen_init(void)
{
    ui_view1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_view1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_view1, &ui_img_flare_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_version = lv_label_create(ui_view1);
    lv_obj_set_width(ui_version, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_version, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_version, 0);
    lv_obj_set_y(ui_version, 50);
    lv_obj_set_align(ui_version, LV_ALIGN_CENTER);
    lv_label_set_text(ui_version, "<Firmware Version>");
    lv_obj_remove_flag(ui_version, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_alertContainer = lv_obj_create(ui_view1);
    lv_obj_remove_style_all(ui_alertContainer);
    lv_obj_set_width(ui_alertContainer, 500);
    lv_obj_set_height(ui_alertContainer, 85);
    lv_obj_set_x(ui_alertContainer, 0);
    lv_obj_set_y(ui_alertContainer, -50);
    lv_obj_set_align(ui_alertContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alertContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_alertContainer,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_alertContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alertContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alertContainer, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_alertContainer, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alertContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alertContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_alertContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_alertContainer, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_alertContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_alertContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_alertContainer, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_alertContainer, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alert = lv_label_create(ui_alertContainer);
    lv_obj_set_width(ui_alert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alert, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alert, "1 .This is an alert\n2. Another one\n3. Oh no!\n4. What happened!?");
}
