#ifndef CONFIG_JSON_EXAMPLE_H
#define CONFIG_JSON_EXAMPLE_H

// Example JSON configuration stored as a constant string
static const char default_config_json[] =
"{\n"
"    \"view\": [{\n"
"        \"enable\": \"Enabled\",\n"
"        \"num_gauges\": 3,\n"
"        \"background\": \"User1\",\n"
"        \"gauge\": [{\n"
"            \"theme\": \"Radial\",\n"
"            \"pid\": \"Engine speed\",\n"
"            \"units\": \"RPM\"\n"
"        }, {\n"
"            \"theme\": \"Radial\",\n"
"            \"pid\": \"Turbocharger compressor inlet pressure\",\n"
"            \"units\": \"PSI\"\n"
"        }, {\n"
"            \"theme\": \"Radial\",\n"
"            \"pid\": \"Engine coolant temperature\",\n"
"            \"units\": \"Fahrenheit\"\n"
"        }]\n"
"    }, {\n"
"        \"enable\": \"Enabled\",\n"
"        \"num_gauges\": 1,\n"
"        \"background\": \"User1\",\n"
"        \"gauge\": [{\n"
"            \"theme\": \"Linear\",\n"
"            \"pid\": \"Turbocharger compressor inlet pressure\",\n"
"            \"units\": \"PSI\"\n"
"        }, {\n"
"            \"theme\": \"Stock ST\",\n"
"            \"pid\": \"\",\n"
"            \"units\": \"None\"\n"
"        }, {\n"
"            \"theme\": \"Stock ST\",\n"
"            \"pid\": \"\",\n"
"            \"units\": \"None\"\n"
"        }]\n"
"    }, {\n"
"        \"enable\": \"Disabled\",\n"
"        \"num_gauges\": 0,\n"
"        \"background\": \"Black\",\n"
"        \"gauge\": [{\n"
"            \"theme\": \"Stock ST\",\n"
"            \"pid\": \"\",\n"
"            \"units\": \"None\"\n"
"        }, {\n"
"            \"theme\": \"Stock ST\",\n"
"            \"pid\": \"\",\n"
"            \"units\": \"None\"\n"
"        }, {\n"
"            \"theme\": \"Stock ST\",\n"
"            \"pid\": \"\",\n"
"            \"units\": \"None\"\n"
"        }]\n"
"    }],\n"
"    \"alert\": [{\n"
"        \"enable\": \"Enabled\",\n"
"        \"pid\": \"Engine speed\",\n"
"        \"units\": \"RPM\",\n"
"        \"message\": \"This is a test of the EEPROM string saving\",\n"
"        \"compare\": \"Greater Than Or Equal To\",\n"
"        \"threshold\": 6500\n"
"    }, {\n"
"        \"enable\": \"Disabled\",\n"
"        \"pid\": \"\",\n"
"        \"units\": \"None\",\n"
"        \"message\": \"This is a test of the EEPROM string saving\",\n"
"        \"compare\": \"Greater Than\",\n"
"        \"threshold\": null\n"
"    }, {\n"
"        \"enable\": \"Disabled\",\n"
"        \"pid\": \"\",\n"
"        \"units\": \"None\",\n"
"        \"message\": \"This is a test of the EEPROM string saving\",\n"
"        \"compare\": \"Greater Than\",\n"
"        \"threshold\": 9.3676505264839584e-38\n"
"    }, {\n"
"        \"enable\": \"Disabled\",\n"
"        \"pid\": \"\",\n"
"        \"units\": \"None\",\n"
"        \"message\": \"This is a test of the EEPROM string saving\",\n"
"        \"compare\": \"Greater Than\",\n"
"        \"threshold\": 3.7615816984235657e-37\n"
"    }, {\n"
"        \"enable\": \"Disabled\",\n"
"        \"pid\": \"\",\n"
"        \"units\": \"None\",\n"
"        \"message\": \"This is a test of the EEPROM string saving\",\n"
"        \"compare\": \"Greater Than\",\n"
"        \"threshold\": 0\n"
"    }],\n"
"    \"dynamic\": [{\n"
"        \"enable\": \"Enabled\",\n"
"        \"priority\": \"High\",\n"
"        \"compare\": \"Greater Than\",\n"
"        \"threshold\": 3000,\n"
"        \"index\": 1,\n"
"        \"pid\": \"Engine speed\",\n"
"        \"units\": \"RPM\"\n"
"    }, {\n"
"        \"enable\": \"Disabled\",\n"
"        \"priority\": \"Low\",\n"
"        \"compare\": \"Less Than Or Equal To\",\n"
"        \"threshold\": 3.9443042910061889e-31,\n"
"        \"index\": 0,\n"
"        \"pid\": \"\",\n"
"        \"units\": \"None\"\n"
"    }]\n"
"}\n";

#endif
