// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DigitalDash-U5-Disco

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_splash
void ui_splash_screen_init(void);
lv_obj_t * ui_splash;
// CUSTOM VARIABLES


// SCREEN: ui_view1
void ui_view1_screen_init(void);
lv_obj_t * ui_view1;
lv_obj_t * ui_gauge1;
lv_obj_t * ui_gauge2;
lv_obj_t * ui_gauge3;
lv_obj_t * ui_needle1;
lv_obj_t * ui_needle2;
lv_obj_t * ui_needle3;
lv_obj_t * ui_value1;
lv_obj_t * ui_value2;
lv_obj_t * ui_value3;
lv_obj_t * ui_pid1;
lv_obj_t * ui_pid2;
lv_obj_t * ui_pid3;
lv_obj_t * ui_version;
lv_obj_t * ui_min1;
lv_obj_t * ui_max1;
lv_obj_t * ui_min2;
lv_obj_t * ui_max2;
lv_obj_t * ui_min3;
lv_obj_t * ui_max4;
lv_obj_t * ui_alertContainer;
lv_obj_t * ui_alert;
// CUSTOM VARIABLES


// SCREEN: ui_view2
void ui_view2_screen_init(void);
lv_obj_t * ui_view2;
lv_obj_t * ui_linear1;
lv_obj_t * ui_pid4;
lv_obj_t * ui_value4;
// CUSTOM VARIABLES


// SCREEN: ui_view3
void ui_view3_screen_init(void);
lv_obj_t * ui_view3;
lv_obj_t * ui_arc1;
lv_obj_t * ui_value5;
lv_obj_t * ui_gauge4;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_gauge[1] = {&ui_img_gauge200_png};
const lv_image_dsc_t * ui_imgset_needle[1] = {&ui_img_needle200_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_splash_screen_init();
    ui_view1_screen_init();
    ui_view2_screen_init();
    ui_view3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_splash);
}
